# Khai Nguyen
#

# define a target for the application
#
all: minunit_example

# define a target to link the application
#
minunit_example: minunit_example.c
	gcc minunit_example.c -o minunit_example

# define a target to clean the directory
#
clean:
	rm -f *.o *.exe
#
# end of file
